### ISSUE TITLE
Translatable labels for newContentElement.wizardItems group

### ISSUE THREAD

**Issue by JBlocks** [b13/container#215]
When structuring the registered containers in different groups, it is currently not possible to set the translation for the "header" group. It will use the `>setGroup('tiles')` name from the container config as a label.

**System:**
- TYPO3 v11.5.x
- Container v1.4.2

**TsConfig: Definition of a language file with translation for the group has no effect**
```
mod {
    wizards {
        newContentElement {
            wizardItems {
              tiles {
                  header = LLL:EXT:acme/Resources/Private/Language/locallang_db.xlf:tiles_group_header
              }
            }
         }
    }
}
```

Would be nice to have translatable labels for newContentElement.wizardItems groups.

![container_newContentElements](https://user-images.githubusercontent.com/9034176/142633741-63c69549-dfe2-43b3-b91c-32558e28ac1d.png)

**Comment by susannemoog** [comment]
The translation has no effect if we add it from an extension by using `ExtensionManagementUtility::addPageTSConfig` as that is added first. The TSConfig of container is loaded by an event which adds it after all the extension tsconfig, making it impossible to overwrite this way. 
However, one can get around that issue by using an own event and loading the TS Config there, for example:

Listener:
```
class PageTsConfig
{
    public function __invoke(ModifyLoadedPageTsConfigEvent $event): void
    {
        $tsConfig = $event->getTsConfig();
        $tsConfig['default'] .= '@import \'EXT:template/Configuration/TsConfig/Root.tsconfig\'';
        $event->setTsConfig($tsConfig);
    }
}
```

Services.yaml
```
  Acme\Template\Listener\PageTsConfig:
    tags:
      - name: event.listener
        identifier: 'tx-template-page-ts-config'
        event: TYPO3\CMS\Core\Configuration\Event\ModifyLoadedPageTsConfigEvent
```
