### ISSUE TITLE
Hidden content in a container is not shown on a connected translation page in free mode

### ISSUE THREAD

**Issue by Tuurlijk** [b13/container#249]
TYPO3 v: 10.4.23
Container v: 1.5.0

**Observed behavior:**
When I have a connected translation in free mode, I have some content outside of a container. The content is hidden on the 'parent' language and the content is shown on the translated page.

The same hidden content inside a container is not shown on the translated page.

**Expected behavior:**
Content hidden inside a container is displayed on the translated page.

Site config:
```yaml
languages:
  -
    title: Europe
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: en_GB
    iso-639-1: en
    navigationTitle: English
    hreflang: en-gb
    direction: ltr
    flag: eu
    websiteTitle: ''
    solr_core_read: core_europe
  -
    title: German
    enabled: true
    base: /de/de/
    typo3Language: de
    locale: de_DE
    iso-639-1: de
    websiteTitle: ''
    navigationTitle: ''
    hreflang: de-DE
    direction: ''
    fallbackType: free
    fallbacks: ''
    flag: de
    languageId: 1    
```

![image](https://user-images.githubusercontent.com/790979/162212560-465b5715-b1b6-4f56-b2de-f8ae108516af.png)
