### ISSUE TITLE
Container content is missing on fallback page in free mode

### ISSUE THREAD

**Issue by terminal8-nz** [b13/container#340]
We had an issue with missing content in the following case:
- the site is in free-mode, a fallback language is defined
- in this case, a page that is not translated will be shown in the defined fallback language
- the content of the page is rendered normally, but the children of all container element are missing

The [ContainerFactory](https://github.com/b13/container/blob/master/Classes/Domain/Factory/PageView/Frontend/ContainerFactory.php#L98) searches the children of an element by the uid of the current languageAspect. I would suggest to search for children in the language of the given container (`$record['sys_language_uid']`) there.

That solved the problem for our case, but the use case is probably not very standard and I'm not sure, if there are other cases where this might lead to problems.

**Comment by achimfritz** [comment]
i will look at that

**Comment by achimfritz** [comment]
@terminal8-nz  mh, works for me (tested with container 2.x, TYPO3 11 and 12). Site-Config:
```
languages:
  -
    title: English
    enabled: true
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    websiteTitle: ''
    navigationTitle: ''
    hreflang: ''
    direction: ''
    flag: gm
    languageId: 0
  -
    title: de
    enabled: true
    base: /de
    typo3Language: de
    locale: de_DE.utf8
    iso-639-1: de
    websiteTitle: ''
    navigationTitle: de
    hreflang: de-DE
    direction: ''
    fallbackType: free
    fallbacks: ''
    flag: de
    languageId: 1
  -
    title: foo
    enabled: true
    base: /xx
    typo3Language: default
    locale: aa_DJ.utf8
    iso-639-1: af
    websiteTitle: ''
    navigationTitle: af
    hreflang: ''
    direction: ''
    fallbackType: free
    fallbacks: '1'
    flag: global
    languageId: 2
```
Contents:
![image](https://user-images.githubusercontent.com/2152991/212267154-391f2b06-6ab6-4e14-8801-3d0a326eeeeb.png)

Frontend in "foo" language:
![image](https://user-images.githubusercontent.com/2152991/212267355-8bea1868-fa43-4752-8ecd-e88149b3394b.png)
