### ISSUE TITLE
Translation in Free Mode broken

### ISSUE THREAD

**Issue by gpazout** [b13/container#384]
The translation of containers in the frontend does not work when having the field "Fallback Type" of a language (that is not the default language) set to "Free Mode"  inside the site config!

**Steps to reproduce:**

1. Make sure the non-default language is set to "Free mode" in the site config (the field is called "Fallback Type")
2. Create a page in your default language (e.g. german)
3. Add CEs to that page (e.g. textmedia outside a b13 container, b13 container, textmedia inside that b13 container, etc.)
4. Translate the page into another language (e.g. english)
5. Translate the CEs of the page into another language (e.g english)
6. Open the frontend of that translated page and you will see that the content inside the b13 container will not be translated!

**siteconfig**:

Mind the `fallbackType: free`!

```
languages:
  -
    title: Default
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE.utf8
    iso-639-1: de
    navigationTitle: DE
    hreflang: de-DE
    direction: ltr
    flag: at
    languageId: '0'
    solr_core_read: core_de
  -
    title: English
    enabled: true
    base: /en/
    typo3Language: default
    locale: en_US.utf8
    iso-639-1: en
    navigationTitle: EN
    hreflang: en-US
    direction: ltr
    fallbackType: free
    fallbacks: '0'
    flag: gb
    languageId: '1'
    solr_core_read: core_en
```

**Versions:**

- Typo3: 11.5.25
- PHP: 8.0.27
- container: 2.2.1
