### ISSUE TITLE
Content Elements are not shown in free mode, strict fallback

### ISSUE THREAD

**Issue by siwa-pparzer** [b13/container#442]
I got following language configuration:

```
languages:
  -
    title: International
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: en_GB.UTF-8
    iso-639-1: en
    navigationTitle: 'International Website (english)'
    hreflang: en
    direction: ltr
    flag: gb
    websiteTitle: ''
  -
    title: Deutschland
    enabled: true
    languageId: 1
    base: /de-de/
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutschland
    hreflang: de
    direction: ltr
    fallbackType: strict
    fallbacks: ''
    flag: de
    websiteTitle: ''
  -
    title: Österreich
    enabled: true
    languageId: 1001
    base: /at-at/
    typo3Language: de
    locale: de_AT
    iso-639-1: de
    navigationTitle: Österreich
    hreflang: de-AT
    direction: ltr
    fallbackType: strict
    fallbacks: '1'
    flag: at
    websiteTitle: ''
```

de-de is translated in free mode, at-at page doesn't exist and falls back to de-de, but no children are shown
if I switch de-de to connected mode, children are processed on at-at
